name: visda
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - pip
  - tqdm
  - numpy
  - ipykernel
  - pandas
  - pytorch=1.10.0
  - torchvision
  - cudatoolkit=11.3.1    